---
- hosts: all
  become: yes
  tasks:
  - name: i wanna install my apache2
    apt:
      name: apache2
      state: latest
  - name: i wanna start my webserver
    service:
      name: apache2
      state: started      