---
- hosts: all
  become: yes
  tasks:
  - name: i wanna install my apache2
    apt:
      name: apache2
      state: latest
  - name: "web Server start"
    service:
       name: "httpd"
       state: started
       enabled: yes     